"""Convert the internal dataset to the verified LeRobot 0.6 writer API."""

from __future__ import annotations

from importlib import metadata
from pathlib import Path
from typing import Any

import numpy as np

from .episode_reader import episode_directories, iter_episode_steps, load_episode_payload

FIELD_MAPPING = {
    "images.front": "observation.images.front",
    "images.wrist": "observation.images.wrist",
    "state": "observation.state",
    "action": "action",
    "task": "task",
    "episode_index": "episode_index (generated by LeRobot)",
    "frame_index": "frame_index (generated by LeRobot)",
    "timestamp": "timestamp (generated as frame_index / fps by LeRobot)",
}


class LeRobotCompatibilityError(RuntimeError):
    """Raised when the installed LeRobot API cannot be safely used."""


def check_lerobot_compatibility() -> str:
    """Require the source-verified LeRobot 0.6.x compatibility window."""
    try:
        version = metadata.version("lerobot")
    except metadata.PackageNotFoundError as exc:
        raise LeRobotCompatibilityError(
            "LeRobot is not installed. Install the verified optional dependency with: "
            "pip install -e '.[lerobot]'"
        ) from exc
    try:
        major, minor = (int(part) for part in version.split(".")[:2])
    except ValueError as exc:
        raise LeRobotCompatibilityError(
            f"Cannot parse installed LeRobot version: {version}"
        ) from exc
    if (major, minor) != (0, 6):
        raise LeRobotCompatibilityError(
            f"LeRobot {version} is outside the verified >=0.6,<0.7 range; re-check the adapter API"
        )
    return version


def _features(payload: dict[str, Any], sample_images: dict[str, np.ndarray]) -> dict[str, Any]:
    state_dim = int(payload["state_dim"])
    action_dim = int(payload["action_dim"])
    features: dict[str, Any] = {
        "observation.state": {"dtype": "float32", "shape": (state_dim,), "names": None},
        "action": {"dtype": "float32", "shape": (action_dim,), "names": None},
    }
    for name, image in sample_images.items():
        features[f"observation.images.{name}"] = {
            "dtype": "image",
            "shape": tuple(image.shape),
            "names": ["height", "width", "channels"],
        }
    return features


def convert_to_lerobot(
    source_dir: str | Path,
    output_dir: str | Path,
    repo_id: str,
    fps: int,
) -> Path:
    """Convert all episodes using LeRobotDataset.create/add_frame/save_episode/finalize."""
    version = check_lerobot_compatibility()
    if fps <= 0:
        raise ValueError("fps must be positive")
    if "/" not in repo_id:
        raise ValueError("repo_id must use the 'namespace/name' form")
    episodes = episode_directories(source_dir)
    if not episodes:
        raise ValueError("Cannot convert an empty dataset")
    target = Path(output_dir)
    if target.exists() and any(target.iterdir()):
        raise FileExistsError(f"Refusing to overwrite non-empty LeRobot dataset: {target}")
    first_step = next(iter_episode_steps(episodes[0], load_images=True))
    payload = load_episode_payload(episodes[0])
    try:
        from lerobot.datasets.lerobot_dataset import LeRobotDataset
    except (ImportError, AttributeError) as exc:
        raise LeRobotCompatibilityError(
            f"LeRobot {version} lacks lerobot.datasets.lerobot_dataset.LeRobotDataset"
        ) from exc
    dataset = LeRobotDataset.create(
        repo_id=repo_id,
        fps=fps,
        features=_features(payload, first_step.observation.images),
        root=target,
        robot_type=str(payload["episode"]["robot_type"]),
        use_videos=False,
    )
    try:
        for episode_dir in episodes:
            for step in iter_episode_steps(episode_dir, load_images=True):
                frame: dict[str, Any] = {
                    "observation.state": np.asarray(step.observation.state, dtype=np.float32),
                    "action": np.asarray(step.action, dtype=np.float32),
                    "task": step.task,
                }
                frame.update(
                    {
                        f"observation.images.{name}": image
                        for name, image in step.observation.images.items()
                    }
                )
                dataset.add_frame(frame)
            dataset.save_episode()
        dataset.finalize()
    except Exception:
        if hasattr(dataset, "clear_episode_buffer"):
            dataset.clear_episode_buffer(delete_images=True)
        raise
    return target
